### ISSUE TITLE
Drop Maven support?

### ISSUE THREAD

**Issue by manuelprinz** [thekrakken/java-grok#32]
The project builds well with Gradle. Travis CI is using Gradle to build it. My IDE gets confused about the two build systems (due to the POM file). Both build systems have to be kept in sync manually. So my question is: Should we drop the POM file / Maven support? Is it really worth maintaining both?

**Comment by anthonycorbacho** [comment]
Yes, I removed maven.
Please see #35

**Comment by anthonycorbacho** [comment]
maven is no longer supported.
