### ISSUE TITLE
Parsed log is getting duplicated or repeated content

### ISSUE THREAD

**Issue by ankitashine132** [thekrakken/java-grok#78]
Hi,

While trying to parse a log, using basic grok exp like this
(?<TYPE>(ERROR))(?<ExceptionTrace>(?m:.*))

The output above expression gives gets duplicated
I have attached log file S3_Spark_Error.txt and log generated output.txt

Please help me on this.

[output.txt](https://github.com/thekrakken/java-grok/files/1585232/output.txt)
[S3_Spark_Error.txt](https://github.com/thekrakken/java-grok/files/1585233/S3_Spark_Error.txt)

**Comment by ottobackwards** [comment]
Do you have a small sample of code that reproduces the problem?
